spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: "${JPA_SHOW_SQL:false}"

server:
  port: "${PORT:${SERVER_PORT:10000}}"
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
